version: "3"
services:
  php-apache:
    image: php:7.2.1-apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpassword"
      MYSQL_DATABASE: "testdb"
